### PR TITLE
Select multiple ingredients

### PR DESCRIPTION
**Pull request by audrow**
This is towards fixing #1.

It currently does what we want, I think, except it doesn't relate ingredients to recipes, because I used simpler datastructures for testing. @mishmishmish, it would be good to let me know if this is closer to what you're looking for and if you'd like anything else.

### CODE REVIEW

**Comment by audrow** [comment]
Oh, and I've put this in a draft because it's not ready to merge into our main branch. As it is, it clobbers a lot of things. But I thought it'd be useful to have you try it.

**Comment by audrow** [comment]
This should now do everything in #1 - take a look!

**Comment by audrow** [comment]
I think probably the best way to proceed here is to try it out and review it. Once you approve it, @mishmishmish, we can merge this in and then you can make another PR styling it.

**Review by mishmishmish — APPROVED** [review]
lgtm!

**Pull request merged**
